resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 400Mi
service:
  # Allow cluster-internal access for image pulls, see also: https://stackoverflow.com/a/64893995
  type: NodePort
  nodePort: 30500
ingress:
  enabled: false
  annotations:
    # kubernetes.io/ingress.class: nginx
    # Allow large image pushes
    # nginx.ingress.kubernetes.io/proxy-body-size: 10g
    cert-manager.io/cluster-issuer: cert-issuer-acme-letsencrypt-staging
