apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: metallb
deploy:
  helm:
    releases:
      - name: metallb
        remoteChart: metallb/metallb
        # See: https://artifacthub.io/packages/helm/metallb/metallb
        version: 0.11.0
        namespace: metallb-system
        createNamespace: true
        wait: true
        upgradeOnChange: true
        valuesFiles:
          # See: https://metallb.universe.tf/installation/
          - values.custom.yaml
