apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: registry-ingress
manifests:
  helm:
    releases:
      - name: docker-registry-ingress
        chartPath: ../../common/general-ingress
        namespace: '{{ index $ "K8S_NAMESPACE" | default "internal" }}'
        createNamespace: true
        wait: true
        skipBuildDependencies: true
        valuesFiles:
          - values.default.yaml
deploy:
  helm: {}
profiles:
  - name: custom
    patches:
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: values.custom.yaml
