apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: jitsi
manifests:
  helm:
    releases:
      - name: jitsi-meet
        # See: https://github.com/jitsi-contrib/jitsi-helm
        remoteChart: jitsi/jitsi-meet
        version: 1.1.0
        namespace: jitsi-meet
        createNamespace: true
        wait: true
        upgradeOnChange: true
        valuesFiles:
          - values.default.yaml
deploy:
  helm: {}
profiles:
  - name: custom
    patches:
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: values.custom.yaml
