apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ingress-nginx
manifests:
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx/ingress-nginx
        # See: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
        version: 4.0.10
        namespace: ingress-nginx
        createNamespace: true
        wait: true
        upgradeOnChange: true
        valuesFiles:
          - values.default.yaml
deploy:
  helm: {}
profiles:
  - name: custom
    patches:
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: values.custom.yaml
  - name: nodeport
    patches:
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: values.nodeport.yaml
