apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: prometheus
deploy:
  helm:
    releases:
      - name: prometheus
        version: 15.1.1
        # See: https://artifacthub.io/packages/helm/prometheus-community/prometheus
        remoteChart: prometheus-community/prometheus
        namespace: prometheus
        createNamespace: true
        wait: true
        upgradeOnChange: true
