apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
spec:
  acme:
    server: {{ .Values.certificate.issuerUrl }}
    email: {{ .Values.certificate.issuerEmail }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-cert-key
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingressClass }}
